import { createHash } from 'node:crypto';
import { readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

const dist = new URL('../dist/', import.meta.url);
const excluded = new Set(['sw.js']);

async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return filesIn(path);
    return entry.isFile() ? [path] : [];
  }));
  return files.flat();
}

const outputFiles = (await filesIn(dist.pathname))
  .filter((path) => !path.endsWith('.map'))
  .filter((path) => !excluded.has(relative(dist.pathname, path).split(sep).join('/')))
  .sort();

const precache = outputFiles.map((path) => `/${relative(dist.pathname, path).split(sep).join('/')}`);
const fingerprint = createHash('sha256');
for (const path of outputFiles) {
  fingerprint.update(path);
  fingerprint.update(await readFile(path));
}
const version = `nlp-${fingerprint.digest('hex').slice(0, 12)}`;

const source = `/* Generated by scripts/generate-sw.mjs. Do not edit this build artifact. */
const VERSION = '${version}';
const SHELL = \`${'${VERSION}'}-shell\`;
const RUNTIME = \`${'${VERSION}'}-runtime\`;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(SHELL).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  // Claim first, before non-essential cache housekeeping. Worker readiness means an
  // active worker, not necessarily a worker controlling this first client;
  // prioritising the claim makes the following navigation reliably offline.
  event.waitUntil(self.clients.claim().then(() =>
    caches.keys().then((keys) => Promise.all(keys
      .filter((key) => ![SHELL, RUNTIME].includes(key))
      .map((key) => caches.delete(key))))
  ));
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).then(async (response) => {
      const copy = response.clone();
      const cache = await caches.open(RUNTIME);
      await cache.put(request, copy);
      return response;
    }).catch(async () => {
      const shell = await caches.open(SHELL);
      return (await shell.match('/index.html', { ignoreVary: true }))
        || (await shell.match('/offline.html', { ignoreVary: true }));
    }));
    return;
  }

  event.respondWith((async () => {
    // cache.addAll() stores the precache request without the page's Origin
    // header. Some otherwise-valid static hosts add Vary: Origin, while
    // controlled module/style requests include that header. The shell consists
    // only of same-origin, revisioned build files, so an ignore-Vary lookup is
    // both safe and required for a portable first offline reload.
    const shell = await caches.open(SHELL);
    const precached = await shell.match(request, { ignoreVary: true });
    if (precached) return precached;

    const cached = await caches.match(request);
    if (cached) return cached;

    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(RUNTIME);
      await cache.put(request, response.clone());
    }
    return response;
  })());
});
`;

await rm(new URL('sw.js', dist), { force: true });
await writeFile(new URL('sw.js', dist), source);
console.log(`Generated service-worker precache (${precache.length} files, ${version}).`);
